#!/bin/bash

echo "Running OSX postinstall"

###############################################################################
# OS settings                                                                 #
###############################################################################

# Dock
defaults write com.apple.dock autohide -bool true
defaults write com.apple.dock persistent-apps -array
defaults write NSGlobalDomain com.apple.swipescrolldirection -bool false


# Top right screen corner → Desktop
defaults write com.apple.dock wvous-tr-corner -int 4
defaults write com.apple.dock wvous-tr-modifier -int 0

###############################################################################
# Safari & WebKit                                                             #
###############################################################################

# Privacy: don’t send search queries to Apple
defaults write com.apple.Safari UniversalSearchEnabled -bool false
defaults write com.apple.Safari SuppressSearchSuggestions -bool true

git config --global core.excludesfile ~/.gitignore_global